In [2]:
import warnings
warnings.filterwarnings("ignore")

#Cargar las funciones auxiliares
from FuncionesRetail import *

#Cargar los datos
ruta_proyecto = 'C:/Users/mcent/OneDrive/Escritorio/MARTIN/MASTERS/DS4B/DATA SCIENCE/03_MACHINE_LEARNING/07_CASOS/FORECASTING RETAIL'
nombre_fichero_datos = 'DatosParaProduccion.csv'
ruta_completa = ruta_proyecto + '/02_Datos/02_Validacion/' + nombre_fichero_datos
df = pd.read_csv(ruta_completa,sep=';',parse_dates=['date'],index_col='date')

#Seleccionar solo las que se han usado
variables_finales = ['store_id',
                     'item_id',
                     'event_name_1',
                     'event_name_2',
                     'month',
                     'sell_price',                      
                     'wday',
                     'weekday',
                     'ventas']

df = df[variables_finales]

#Lanzar la predicci√≥n
forecast = forecast_recursivo(df).sort_values(by = ['store_id','item_id'])

In [5]:
forecast.head(15)

,store_id,item_id,event_name_1,event_name_2,month,sell_price,wday,weekday,ventas
date,,,,,,,,,
2015-12-17,CA_3,FOODS_3_090,NaN,NaN,12,1.0,6,Thursday,0
2015-12-18,CA_3,FOODS_3_090,NaN,NaN,12,1.0,7,Friday,1
2015-12-19,CA_3,FOODS_3_090,NaN,NaN,12,1.0,1,Saturday,0
2015-12-20,CA_3,FOODS_3_090,NaN,NaN,12,1.0,2,Sunday,6
2015-12-21,CA_3,FOODS_3_090,NaN,NaN,12,1.0,3,Monday,4
2015-12-22,CA_3,FOODS_3_090,NaN,NaN,12,1.0,4,Tuesday,5
2015-12-23,CA_3,FOODS_3_090,NaN,NaN,12,1.0,5,Wednesday,2
2015-12-24,CA_3,FOODS_3_090,Chanukah End,0.0,12,1.0,6,Thursday,13
2015-12-25,CA_3,FOODS_3_090,Christmas,0.0,12,1.0,7,Friday,24
2015-12-26,CA_3,FOODS_3_090,NaN,0.0,12,1.0,1,Saturday,-5
2015-12-27,CA_3,FOODS_3_090,NaN,0.0,12,1.0,2,Sunday,-5
2015-12-28,CA_3,FOODS_3_090,NaN,0.0,12,1.0,3,Monday,4
2015-12-29,CA_3,FOODS_3_090,NaN,0.0,12,1.0,4,Tuesday,83
2015-12-30,CA_3,FOODS_3_090,NaN,0.0,12,1.0,5,Wednesday,111
2015-12-31,CA_3,FOODS_3_090,NaN,0.0,12,1.0,6,Thursday,127